const { Transformer } = require('markmap-lib');

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).send('Method Not Allowed');

  try {
    const { content, style } = req.body;
    
    const transformer = new Transformer();
    // transform 返回的是根节点对象
    const { root } = transformer.transform(content || '# 无内容');

    // 配色方案
    const colors = [
      style?.rootBgColor || '#E7F3FF', 
      '#FFF0F0', 
      '#F0FFF0', 
      '#FFFFF0'
    ];
    
    // 递归生成 HTML 的函数 (已修复属性名问题)
    function renderNode(node, depth = 0, isLast = false) {
      if (!node) return '';
      
      // --- 关键修改点 START ---
      // 兼容新旧版本的字段名
      const nodeText = node.content || node.v || ''; 
      const childrenList = node.children || node.c || [];
      // --- 关键修改点 END ---

      const hasChildren = childrenList.length > 0;
      
      // 样式定义
      const bgColor = depth === 0 ? colors[0] : '#FFFFFF';
      const textColor = depth === 0 ? (style?.rootTextColor || '#1890FF') : '#333';
      const fontSize = depth === 0 ? '18px' : '15px';
      const fontWeight = depth === 0 ? 'bold' : 'normal';
      const padding = depth === 0 ? '10px 20px' : '8px 12px';
      const borderRadius = '6px';
      const boxShadow = '0 2px 4px rgba(0,0,0,0.05)';
      const border = depth === 0 ? `2px solid ${style?.rootBgColor || '#1890FF'}` : '1px solid #ddd';
      const lineColor = '#ddd'; 

      // 构建子节点 HTML
      let childrenHtml = '';
      if (hasChildren) {
        childrenHtml = `<div style="display: flex; flex-direction: column; justify-content: center; margin-left: 20px; border-left: 2px solid ${lineColor};">`;
        
        childrenList.forEach((child, index) => {
          const isChildLast = index === childrenList.length - 1;
          const connectorStyle = `position: relative; padding-left: 15px; margin: 5px 0;`;
          const horizontalLine = `<div style="position: absolute; left: 0; top: 50%; width: 15px; height: 2px; background-color: ${lineColor};"></div>`;
          const coverLine = isChildLast ? `<div style="position: absolute; left: -2px; top: 50%; bottom: 0; width: 4px; background-color: #fff;"></div>` : '';

          childrenHtml += `
            <div style="${connectorStyle}">
              ${horizontalLine}
              ${coverLine}
              ${renderNode(child, depth + 1, isChildLast)}
            </div>
          `;
        });
        childrenHtml += `</div>`;
      }

      // 构建当前节点 HTML
      // 注意这里使用了 nodeText 变量
      const nodeHtml = `
        <div style="
          background: ${bgColor}; 
          color: ${textColor}; 
          font-size: ${fontSize}; 
          font-weight: ${fontWeight}; 
          padding: ${padding}; 
          border-radius: ${borderRadius}; 
          border: ${border};
          box-shadow: ${boxShadow};
          display: inline-block;
          min-width: 50px;
          position: relative;
          z-index: 2;
        ">${nodeText}</div>
      `;

      // 组合布局
      const wrapperStyle = depth === 0 
        ? "display: flex; align-items: center; font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;"
        : "display: flex; align-items: center;";

      return `
        <div style="${wrapperStyle}">
          ${nodeHtml}
          ${hasChildren ? `<div style="width: 20px; height: 2px; background-color: ${lineColor};"></div>` : ''}
          ${childrenHtml}
        </div>
      `;
    }

    const finalHtml = `
      <section style="overflow-x: auto; padding: 20px; background: #fff;">
        ${renderNode(root)}
        <div style="text-align: center; margin-top: 20px; color: #ccc; font-size: 12px;">
           Generated by n8n Flow
        </div>
      </section>
    `;

    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(finalHtml);

  } catch (error) {
    console.error(error);
    res.status(500).send(`Error: ${error.message}`);
  }
};
